services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi
    restart: unless-stopped
    environment:
      PORT: 8000

networks:
  default:
    external: true
    name: scoobydoo
